project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - themes/*.qmd
  resources:
    - screenshots/

website:
  title: Quarto Reveal.js Themes
  site-url: https://jansim.github.io/quarto-revealjs-themes/
  repo-url: https://github.com/jansim/quarto-revealjs-themes
  navbar:
    right:
      - icon: github
        href: https://github.com/jansim/quarto-revealjs-themes

format:
  html:
    theme: [default, site.scss]
